import type { Metadata } from 'next';
import localFont from 'next/font/local';
import CssBaseline from '@mui/material/CssBaseline';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/app/theme';
const basisGrotesquePro = localFont({
  src: [
    {
      path: '../assets/fonts/BasisGrotesquePro-Bold.ttf',
      weight: '700',
      style: 'normal'
    },
    {
      path: '../assets/fonts/BasisGrotesquePro-Medium.ttf',
      weight: '500',
      style: 'normal'
    },
    {
      path: '../assets/fonts/BasisGrotesquePro-Light.ttf',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../assets/fonts/BasisGrotesquePro-Regular.ttf',
      weight: '300',
      style: 'normal'
    }
  ]
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create @N4G1B4T0R'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={basisGrotesquePro.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
